name: CI

on:
    push:
        branches:
            - main
    workflow_dispatch: 

jobs:
    unit-tests-backend:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            checks: write
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"
                  cache-dependency-path: bugtracker-backend/go.sum

            - name: Install go-junit-report
              run: go install github.com/jstemmer/go-junit-report/v2@latest      

            - name: Execute Backend Unit Tests
              working-directory: ./bugtracker-backend
              run: |
                  go test -v ./... 2>&1 | go-junit-report > test-results.xml

            - name: Publish backend test results
              uses: dorny/test-reporter@v1
              if: always()
              with:
                 name: Backend Unit Tests Report
                 path: bugtracker-backend/test-results.xml
                 reporter: jest-junit

    unit-tests-frontend:
        #needs: unit-tests-backend
        #If you remove the needs from this section it will run in parallel 
        runs-on: ubuntu-latest
        permissions:
            contents: read
            checks: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: bugtracker-frontend/package-lock.json

            - name: Execute Frontend Unit Tests
              working-directory: ./bugtracker-frontend
              run: |
                  npm ci
                  npm test | tee full_output.txt

                  echo "## Frontend Test Coverage Report" >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY
                  cat full_output.txt >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY

            - name: Publish Frontend Test Results
              uses: dorny/test-reporter@v1
              if: always ()
              with:
                 name: Frontend Unit Tests Report
                 path: bugtracker-frontend/test-results.xml
                 reporter: jest-junit
    api-tests-e2e:
        needs: [unit-tests-backend, unit-tests-frontend]
        runs-on: ubuntu-latest
        permissions:
            contents: read
            checks: write
            pull-requests: write
        steps: 
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Launch App
              run: |
                docker compose up --build -d
                npx wait-port http://localhost:8080/api/health -t 30000

            - name: Run API Test
              working-directory: ./tests-api
              run: |
                npm ci
                npx playwright test

            - name: Run E2E Tests
              working-directory: ./tests-e2e
              run: |
                npm ci
                npx playwright install
                npx playwright test

            - name: Shut Down App
              run: docker compose down

            - name: Upload API test results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: api-test-results
                path: ./tests-api/test-results/
                retention-days: 15

            - name: Upload API test Playwright Reports
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: api-test-playwright-report
                path: ./tests-api/playwright-report/
                retention-days: 15

            - name: Upload E2E Test Results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: e2e-tests-results
                path: ./tests-e2e/tests-results
                retention-days: 15

            - name: Publish E2E Test Restults
              uses: dorny/test-reporter@v1
              if: always()
              with:
                name: E2E Test Report
                path: ./tests-e2e/test-results/results.xml
                reporter: jest-junit

            - name: Publish API Test Restults
              uses: dorny/test-reporter@v1
              if: always()
              with:
                name: API Test Report
                path: ./tests-api/test-results/results.xml
                reporter: jest-junit
    

            

          

    